# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "mm_quickbottles"

# Version of this mod.
version = "1.1.4"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "Quick Bottles"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """
This mod binds your bottles to L, moving the minimap toggle to the mod menu.

Tap L to use a bottle. Hold L and use the DPad to select one.
"""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "Quick access to all your bottles with L."

# Authors of this mod.
authors = [ "LT_Schmiddy" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
# Example dependency:
#    "modname:1.0.0"
    "ProxyMM_KV:0.0.5"
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
# Example native library:
#    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "mm_quickbottles"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

# Additional files to include in the mod.
additional_files = [ "thumb.dds" ]

[[manifest.config_options]]
id = "minimap-visible"
name = "Minimap Visible"
description = "This mod completely repurposes the button normally used for toggling the minimap. Toggle it here instead."
type = "Enum"
options = [ "On", "Off" ]
default = "On"

[[manifest.config_options]]
id = "bottle-hud-layout"
name = "Bottle Hud Layout"
description = """
The Layout of the Bottle HUD. DPad selection inputs are configured to match.

Normally, an empty space will be drawn for any bottle the player doesn't have. The 'Gapless' variants eliminate this space.

1 = Single
2 = Horizontal
3 = Vertical - Bottom Up
4 = Vertical - Top Down
5 = Two Rows
6 = Two Columns
7 = Horizontal - Gapless
8 = Vertical - Bottom Up - Gapless
9 = Vertical - Top Down - Gapless

"""
type = "Enum"
options = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
default = "2"

[[manifest.config_options]]
id = "bottle-selection-style"
name = "Bottle Selection Style"
description = """How should the Bottle HUD indicate the selected bottle:
Fade - All unselected bottles will be rendered at less that full transparancy.
Border - The Item Equip border will be drawn around the selected bottle.
"""


type = "Enum"
options = [ "Fade", "Border", ]
default = "Fade"

[[manifest.config_options]]
id = "bottle-round-robin"
name = "Round Robin Mode"
description = """
Selected Bottle is always shown in the first position.

The 'Reverse' mirrors the DPad selection inputs along both axes, which may feel more natural to some players using this mode.
"""
type = "Enum"
options = [ "Off", "On", "Reverse" ]
default = "Off"

[[manifest.config_options]]
id = "bottle-autohide"
name = "Autohide"
description = """
While holding L it will respect your selected Bottle Hud Layout as normal. Otherwise, the selected bottle is shown in the first position and the others are hidden.

When set to 'On' the quick_press duration must expire before showing all bottles. 'Instant' shows all bottles right away (meaning they will appear when you simply want to use a bottle). 
"""
type = "Enum"
options = [ "Off", "On", "Instant" ]
default = "Off"

[[manifest.config_options]]
id = "bottle-quick-press-time"
name = "Quick Press Time"
description = """
How long you are allowed to hold L to use the selected bottle.

It's recommended to keep Quick Press Time at around 5 for Autohide, and around 10 without Autohide.
"""
type = "Number"
min = 1
max = 15
step = 1
precision = 1
percent = false
default = 10

[[manifest.config_options]]
id = "bottle-equipslots"
name = "Use Equip Slots"
description = """
When you equip a bottle to a C button, that button is used as a quick bottles slot.
"""
type = "Enum"
options = [ "Off", "On" ]
default = "Off"